export interface TriviaQuestion {
  id: number;
  pregunta: string;
  opciones: [string, string, string, string];
  respuesta_correcta: 0 | 1 | 2 | 3;
  dificultad: "fácil" | "media" | "difícil";
}

export const QUESTIONS: TriviaQuestion[] = [
  // ── FÁCIL (1–25) ────────────────────────────────────────────────────────────
  {
    id: 1,
    pregunta: "¿Cuántos títulos mundiales ha ganado Brasil?",
    opciones: ["3", "4", "5", "6"],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 2,
    pregunta: "¿Qué selección ganó el primer Mundial de Fútbol en 1930?",
    opciones: ["Argentina", "Uruguay", "Brasil", "Italia"],
    respuesta_correcta: 1,
    dificultad: "fácil",
  },
  {
    id: 3,
    pregunta: "¿En qué país se celebró el primer Mundial de Fútbol (1930)?",
    opciones: ["Argentina", "Brasil", "Uruguay", "Francia"],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 4,
    pregunta: "¿Cuántos títulos mundiales ha ganado Italia?",
    opciones: ["3", "4", "5", "6"],
    respuesta_correcta: 1,
    dificultad: "fácil",
  },
  {
    id: 5,
    pregunta: "¿Cuántos títulos mundiales ha ganado Argentina?",
    opciones: ["2", "3", "4", "5"],
    respuesta_correcta: 1,
    dificultad: "fácil",
  },
  {
    id: 6,
    pregunta: "¿Cuántas finales mundiales ha disputado Brasil?",
    opciones: ["4", "5", "6", "7"],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 7,
    pregunta: "¿Qué selección ganó el Mundial de Qatar 2022?",
    opciones: ["Francia", "Brasil", "Alemania", "Argentina"],
    respuesta_correcta: 3,
    dificultad: "fácil",
  },
  {
    id: 8,
    pregunta: "¿Qué selección ganó el Mundial de Estados Unidos 1994?",
    opciones: ["Italia", "Argentina", "Brasil", "Alemania"],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 9,
    pregunta: "¿Cuál fue el marcador de la mayor goleada en la historia del Mundial?",
    opciones: [
      "Yugoslavia 9-0 Zaire",
      "Hungría 9-0 Corea del Sur",
      "Hungría 10-1 El Salvador",
      "Uruguay 8-0 Bolivia",
    ],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 10,
    pregunta: "¿Qué partido acumula más goles totales en la historia del Mundial?",
    opciones: [
      "Hungría 10-1 El Salvador",
      "Hungría 8-3 Alemania Occidental",
      "Austria 7-5 Suiza",
      "Brasil 6-5 Polonia",
    ],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 11,
    pregunta: "¿En qué año se celebró el primer Mundial de Fútbol masculino?",
    opciones: ["1928", "1930", "1932", "1934"],
    respuesta_correcta: 1,
    dificultad: "fácil",
  },
  {
    id: 12,
    pregunta: "¿Qué país tiene más victorias en la historia del Mundial masculino?",
    opciones: ["Argentina", "Alemania", "Italia", "Brasil"],
    respuesta_correcta: 3,
    dificultad: "fácil",
  },
  {
    id: 13,
    pregunta: "¿Qué selección ganó el Mundial de Francia 1998?",
    opciones: ["Brasil", "Alemania", "Francia", "Italia"],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 14,
    pregunta: "¿Qué selección tiene más goles a favor en la historia del Mundial?",
    opciones: ["Alemania", "Argentina", "Brasil", "Francia"],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 15,
    pregunta: "¿Cuántos Mundiales masculinos se han disputado entre 1930 y 2022?",
    opciones: ["20", "21", "22", "24"],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 16,
    pregunta: "¿Qué selección ganó el Mundial de Sudáfrica 2010?",
    opciones: ["Brasil", "Alemania", "Argentina", "España"],
    respuesta_correcta: 3,
    dificultad: "fácil",
  },
  {
    id: 17,
    pregunta: "¿Qué selección ganó el Mundial de Alemania 2006?",
    opciones: ["Alemania", "Francia", "Italia", "Portugal"],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 18,
    pregunta: "¿Qué selección ganó el Mundial de Brasil 2014?",
    opciones: ["Argentina", "Brasil", "España", "Alemania"],
    respuesta_correcta: 3,
    dificultad: "fácil",
  },
  {
    id: 19,
    pregunta: "¿Brasil es el único país que ha participado en todos los Mundiales masculinos disputados?",
    opciones: [
      "No, también Alemania",
      "No, también Argentina",
      "Sí, los 22 mundiales",
      "No, también México",
    ],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 20,
    pregunta: "¿Con qué resultado terminó la primera final del Mundial (Uruguay vs Argentina, 1930)?",
    opciones: [
      "Uruguay 3-2 Argentina",
      "Uruguay 4-2 Argentina",
      "Uruguay 2-1 Argentina",
      "Uruguay 4-1 Argentina",
    ],
    respuesta_correcta: 1,
    dificultad: "fácil",
  },
  {
    id: 21,
    pregunta: "¿Qué selección ganó el Mundial de Corea-Japón 2002?",
    opciones: ["Alemania", "Brasil", "Turquía", "Corea del Sur"],
    respuesta_correcta: 1,
    dificultad: "fácil",
  },
  {
    id: 22,
    pregunta: "¿Con qué goleada aplastó Yugoslavia a Zaire en el Mundial de 1974?",
    opciones: ["8-0", "9-0", "7-0", "6-0"],
    respuesta_correcta: 1,
    dificultad: "fácil",
  },
  {
    id: 23,
    pregunta: "¿Qué selección ganó el Mundial de Inglaterra 1966?",
    opciones: ["Alemania Occidental", "Portugal", "Uruguay", "Inglaterra"],
    respuesta_correcta: 3,
    dificultad: "fácil",
  },
  {
    id: 24,
    pregunta: "¿Cuántos mundiales ha disputado México (1930-2022)?",
    opciones: ["15", "16", "17", "18"],
    respuesta_correcta: 2,
    dificultad: "fácil",
  },
  {
    id: 25,
    pregunta: "¿En cuántos mundiales ha participado Brasil (único que no se ha perdido ninguno)?",
    opciones: ["19", "20", "21", "22"],
    respuesta_correcta: 3,
    dificultad: "fácil",
  },

  // ── MEDIA (26–55) ────────────────────────────────────────────────────────────
  {
    id: 26,
    pregunta: "¿Cuántas victorias acumula Brasil en la historia del Mundial masculino?",
    opciones: ["68", "73", "79", "85"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 27,
    pregunta: "¿Cuántos goles ha marcado Brasil en total en la historia del Mundial?",
    opciones: ["205", "220", "237", "252"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 28,
    pregunta: "¿Cuántas victorias acumula Argentina en la historia del Mundial?",
    opciones: ["47", "53", "58", "62"],
    respuesta_correcta: 1,
    dificultad: "media",
  },
  {
    id: 29,
    pregunta: "¿Cuántos goles marcó Hungría en el Mundial de 1954 (récord de goles por equipo en un torneo)?",
    opciones: ["23", "25", "27", "29"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 30,
    pregunta: "¿Qué pareja de selecciones se ha enfrentado más veces en la historia del Mundial?",
    opciones: ["Argentina-Brasil", "Brasil-Italia", "Brasil-Suecia", "Argentina-Alemania"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 31,
    pregunta: "¿Cuántos encuentros han tenido Brasil y Suecia en Mundiales (el duelo más frecuente)?",
    opciones: ["5", "6", "7", "8"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 32,
    pregunta: "¿Cuántos goles marcó Francia en el Mundial de 1958 (tercer registro histórico por equipo)?",
    opciones: ["19", "21", "23", "25"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 33,
    pregunta: "¿Cuántas selecciones distintas han participado en el Mundial masculino entre 1930 y 2022?",
    opciones: ["72", "78", "81", "88"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 34,
    pregunta: "¿En qué Mundial se jugó el Austria 7-5 Suiza, el partido con más goles de la historia?",
    opciones: ["1950", "1954", "1958", "1962"],
    respuesta_correcta: 1,
    dificultad: "media",
  },
  {
    id: 35,
    pregunta: "¿Cuántas veces se han enfrentado Argentina y Países Bajos en Mundiales?",
    opciones: ["4", "5", "6", "7"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 36,
    pregunta: "¿Cuántos goles ha marcado Francia en toda la historia del Mundial?",
    opciones: ["121", "128", "136", "143"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 37,
    pregunta: "¿Cuántos goles marcó Alemania Occidental en el Mundial de 1954 (segundo registro histórico)?",
    opciones: ["21", "23", "25", "27"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 38,
    pregunta: "¿Cuántas finales mundiales ha disputado Países Bajos?",
    opciones: ["2", "3", "4", "5"],
    respuesta_correcta: 1,
    dificultad: "media",
  },
  {
    id: 39,
    pregunta: "¿Cuántas finales mundiales ha disputado Argentina?",
    opciones: ["4", "5", "6", "7"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 40,
    pregunta: "¿Cuántas finales mundiales ha disputado Alemania Occidental?",
    opciones: ["4", "5", "6", "7"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 41,
    pregunta: "¿Cómo se definió la final del Mundial de 1994 (la primera en ir a penales)?",
    opciones: [
      "Brasil 1-0 Italia",
      "Brasil 0-0 Italia (3-2 en penales)",
      "Italia 0-0 Brasil (4-3 en penales)",
      "Brasil 2-1 Italia",
    ],
    respuesta_correcta: 1,
    dificultad: "media",
  },
  {
    id: 42,
    pregunta: "¿Cómo terminó la final del Mundial de 2006 entre Italia y Francia?",
    opciones: [
      "Italia 2-1 Francia",
      "Italia 1-1 Francia (5-3 en penales)",
      "Francia 1-1 Italia (4-3 en penales)",
      "Italia 2-0 Francia",
    ],
    respuesta_correcta: 1,
    dificultad: "media",
  },
  {
    id: 43,
    pregunta: "¿Con cuántos goles de diferencia venció Hungría a El Salvador en el Mundial de 1982?",
    opciones: ["7", "8", "9", "10"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 44,
    pregunta: "¿En qué año ganó Uruguay su segundo título mundial?",
    opciones: ["1938", "1942", "1946", "1950"],
    respuesta_correcta: 3,
    dificultad: "media",
  },
  {
    id: 45,
    pregunta: "¿Cuántos empates tiene Inglaterra en la historia del Mundial (el récord absoluto)?",
    opciones: ["14", "16", "18", "21"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 46,
    pregunta: "¿Cuántos goles ha marcado Argentina en la historia del Mundial?",
    opciones: ["141", "152", "163", "175"],
    respuesta_correcta: 1,
    dificultad: "media",
  },
  {
    id: 47,
    pregunta: "¿Cuántos goles marcó Brasil en el Mundial de 1950?",
    opciones: ["18", "20", "22", "24"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 48,
    pregunta: "¿Cuántas victorias tiene Francia en la historia del Mundial?",
    opciones: ["35", "38", "41", "44"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 49,
    pregunta: "¿Cuántas veces se han enfrentado Argentina e Inglaterra en Mundiales?",
    opciones: ["3", "4", "5", "6"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 50,
    pregunta: "¿Cuántos goles ha marcado España en la historia del Mundial?",
    opciones: ["96", "102", "108", "114"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 51,
    pregunta: "¿Con qué resultado debutó Francia en el primer partido de la historia del Mundial (13 julio 1930)?",
    opciones: [
      "Francia 3-0 México",
      "Francia 4-1 México",
      "Francia 2-0 México",
      "Francia 5-1 México",
    ],
    respuesta_correcta: 1,
    dificultad: "media",
  },
  {
    id: 52,
    pregunta: "¿Cuántos goles ha marcado Países Bajos en la historia del Mundial?",
    opciones: ["84", "90", "96", "102"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 53,
    pregunta: "¿En qué ronda se jugó el histórico Austria 7-5 Suiza en el Mundial de 1954?",
    opciones: ["Segunda fase de grupos", "Octavos de final", "Cuartos de final", "Semifinal"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 54,
    pregunta: "¿Cuántas finales mundiales ha disputado Italia?",
    opciones: ["4", "5", "6", "7"],
    respuesta_correcta: 2,
    dificultad: "media",
  },
  {
    id: 55,
    pregunta: "¿Qué resultado tuvo la final del Mundial de 2022 entre Argentina y Francia?",
    opciones: [
      "Argentina 2-0 Francia",
      "Argentina 3-2 Francia",
      "Argentina 3-3 Francia (4-2 en penales)",
      "Argentina 2-1 Francia",
    ],
    respuesta_correcta: 2,
    dificultad: "media",
  },

  // ── DIFÍCIL (56–70) ──────────────────────────────────────────────────────────
  {
    id: 56,
    pregunta: "¿Cuál es el porcentaje exacto de victorias de Brasil en el Mundial (en 114 partidos jugados)?",
    opciones: ["65.1%", "67.8%", "69.3%", "71.5%"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 57,
    pregunta: "¿Cuál es el porcentaje de victorias de Croacia en el Mundial (con 30 partidos jugados)?",
    opciones: ["52.3%", "54.0%", "56.7%", "59.1%"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 58,
    pregunta: "¿Cuántos goles marcó Brasil en el Mundial de 1970 (el torneo de Pelé)?",
    opciones: ["16", "17", "18", "19"],
    respuesta_correcta: 3,
    dificultad: "difícil",
  },
  {
    id: 59,
    pregunta: "¿Cuántos goles ha marcado Italia en toda la historia del Mundial?",
    opciones: ["118", "123", "128", "133"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 60,
    pregunta: "¿Cuántos goles ha marcado Uruguay en la historia del Mundial?",
    opciones: ["79", "84", "89", "94"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 61,
    pregunta: "¿Cuántas victorias tiene Países Bajos en la historia del Mundial?",
    opciones: ["27", "29", "31", "33"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 62,
    pregunta: "¿Cuántos empates tiene Italia en la historia del Mundial?",
    opciones: ["13", "15", "17", "19"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 63,
    pregunta: "¿Cuántos empates tiene México en la historia del Mundial?",
    opciones: ["10", "11", "12", "13"],
    respuesta_correcta: 3,
    dificultad: "difícil",
  },
  {
    id: 64,
    pregunta: "¿Cuál es el promedio histórico de goles por partido en el Mundial masculino?",
    opciones: ["2.45", "2.62", "2.82", "3.05"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 65,
    pregunta: "¿Cuántas victorias tiene Alemania (reunificada, excluyendo Alemania Occidental) en el Mundial?",
    opciones: ["27", "30", "33", "36"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 66,
    pregunta: "¿Cuántas victorias tiene Uruguay en la historia del Mundial?",
    opciones: ["21", "24", "26", "29"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 67,
    pregunta: "¿Cuántas victorias tiene España en la historia del Mundial?",
    opciones: ["27", "29", "32", "35"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 68,
    pregunta: "¿Cuántos goles ha marcado Alemania Occidental en la historia del Mundial?",
    opciones: ["118", "125", "131", "137"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 69,
    pregunta: "¿Cuántas victorias tiene Alemania Occidental en la historia del Mundial?",
    opciones: ["34", "37", "39", "42"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
  {
    id: 70,
    pregunta: "¿Cuántos goles ha marcado Alemania (reunificada, excluyendo Alemania Occidental) en el Mundial?",
    opciones: ["89", "94", "101", "107"],
    respuesta_correcta: 2,
    dificultad: "difícil",
  },
];
